In [525]:
import pandas as pd
import numpy as np

In [2]:
df_train = pd.read_csv('TRAIN - TRAIN.csv.csv')
df_train.head()

[('DF', 'PROPN')]
0  [('03/01/2001', 'NUM'), ('01:35', 'NUM'), ('PM...
1  [('The', 'DET'), ('industry', 'NOUN'), ('has',...
2  [('Love', 'VERB'), ('this', 'DET'), ('place', ...
3  [('This', 'DET'), ('problem', 'NOUN'), ('of', ...
4  [('Esso', 'PROPN'), ('said', 'VERB'), ('0', 'X...

In [3]:
df_test = pd.read_csv('TEST - TEST.csv.csv')
df_test

[('DF', 'PROPN')]
0      [('03/01/2001', 'NUM'), ('01:35', 'NUM'), ('PM...
1      [('The', 'DET'), ('industry', 'NOUN'), ('has',...
2      [('Love', 'VERB'), ('this', 'DET'), ('place', ...
3      [('This', 'DET'), ('problem', 'NOUN'), ('of', ...
4      [('Esso', 'PROPN'), ('said', 'VERB'), ('0', 'X...
...                                                  ...
65619  [('Thus', 'ADV'), (',', '.'), ('paradoxically'...
65620  [('Someone', 'NOUN'), ('reasonably', 'ADV'), (...
65621  [('During', 'ADP'), ('this', 'DET'), ('search'...
65622  [('Thank', 'VERB'), ('you', 'PRON'), ('for', '...
65623  [("Today's", 'NOUN'), ('earthquakes', 'NOUN'),...

[65624 rows x 1 columns]

In [4]:
x=df_train.iloc[0,-1]
x

"[('03/01/2001', 'NUM'), ('01:35', 'NUM'), ('PM', 'NOUN')]"

In [5]:
df_train.shape

(52499, 1)

In [6]:
vocabulary= set()
tags = set()
for line in df_train.iloc[0:-1,0]:
    data = eval(line)  
    for word, tag in data:
        vocabulary.add(word)
        tags.add(tag)

In [7]:
vocabulary

{'mealie-meal',
 'learners',
 'Booty',
 'MUST',
 'pager',
 'excision',
 'Rude',
 'crisis',
 'Cabernets',
 'autobiographic',
 'ruthless',
 'Frequently',
 'copyrights',
 'MUCH',
 'investigations',
 'Ennis',
 'editorially',
 'Adherence',
 'refuses',
 'sections',
 'reorganization',
 'Illuminating',
 'resonant',
 'Tho',
 'granular',
 'reinvestigation',
 '$109',
 'saucepan',
 'refugees',
 'reward',
 'Lisbon',
 'expansion-contraction',
 'Pontchartrain',
 'submariners',
 'Sullam',
 'WSI',
 'unfilled',
 'Philippi',
 'nice',
 'Antique',
 'infrastructure',
 'swamping',
 'hydrated',
 'both',
 'streamliner',
 'Crest',
 'cheque',
 'coloring',
 'Merle',
 'snugly',
 'profit-motivated',
 'Erection',
 '6th',
 'Swallow-Barn',
 'Flannagans',
 'travelogue',
 '!!!!!!!!!!!!!!!!!!!!!',
 'refineries',
 'Sheila',
 'Kronenberger',
 'glycerine',
 'four-letter',
 'Lehner',
 'Brisbane',
 'all-victorious',
 'obligated',
 'F',
 'insuperable',
 'rockers',
 'Iglehart',
 'M.P.',
 'obtainable',
 'fables',
 'ER',
 'meande

In [8]:
tags

{'.',
 'ADJ',
 'ADP',
 'ADV',
 'AUX',
 'CCONJ',
 'CONJ',
 'DET',
 'INTJ',
 'NOUN',
 'NUM',
 'PART',
 'PRON',
 'PROPN',
 'PRT',
 'PUNCT',
 'SCONJ',
 'SYM',
 'VERB',
 'X',
 '_'}

In [9]:
print(f"{len(vocabulary)},{len(tags)}")

58110,21


In [189]:
idx =0
idx1=1
vocab2idx ={}
tag2idx={}
for doc in df_train.iloc[0:-1,0]:
    words = eval(doc)
    for word,tag in words:
        if word not in vocab2idx:
            vocab2idx[word]=idx
            idx+=1
        if tag not in tag2idx:
            tag2idx[tag]=idx1
            idx1+=1
   

In [190]:
vocab2idx

{'03/01/2001': 0,
 '01:35': 1,
 'PM': 2,
 'The': 3,
 'industry': 4,
 'has': 5,
 'said': 6,
 '1960': 7,
 'was': 8,
 'a': 9,
 'poor': 10,
 'year': 11,
 '.': 12,
 'Love': 13,
 'this': 14,
 'place': 15,
 '!!': 16,
 'This': 17,
 'problem': 18,
 'of': 19,
 'the': 20,
 'optimum': 21,
 'balance': 22,
 'in': 23,
 'relative': 24,
 'numbers': 25,
 'generalists': 26,
 'and': 27,
 'specialists': 28,
 'can': 29,
 'be': 30,
 'investigated': 31,
 'on': 32,
 'communicative': 33,
 'network': 34,
 'basis': 35,
 'Esso': 36,
 '0': 37,
 'Whiting': 38,
 'field': 39,
 'started': 40,
 'production': 41,
 'Tuesday': 42,
 'He': 43,
 'drew': 44,
 'deep': 45,
 'breath': 46,
 'Glendora': 47,
 "''": 48,
 '--': 49,
 'Each': 50,
 'side': 51,
 'litany': 52,
 'recommendations': 53,
 'for': 54,
 'other': 55,
 'In': 56,
 'symposium': 57,
 'general': 58,
 'exploration': 59,
 'Personal': 60,
 'Perception': 61,
 'Interpersonal': 62,
 'Behavior': 63,
 'discussion': 64,
 'does': 65,
 'not': 66,
 'touch': 67,
 'upon': 68,
 'aspe

In [191]:
len(vocab2idx)

58110

In [192]:
len(tag2idx)

21

In [193]:
tag2idx['DET']

3

In [215]:
em=np.zeros((len(vocab2idx),len(tag2idx)+1)) 

In [216]:
em

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [196]:
tag2idx

{'NUM': 1,
 'NOUN': 2,
 'DET': 3,
 'VERB': 4,
 'ADJ': 5,
 '.': 6,
 'PUNCT': 7,
 'ADP': 8,
 'CONJ': 9,
 'PROPN': 10,
 'X': 11,
 'PRON': 12,
 'ADV': 13,
 'AUX': 14,
 'INTJ': 15,
 'CCONJ': 16,
 'PRT': 17,
 'PART': 18,
 'SCONJ': 19,
 '_': 20,
 'SYM': 21}

In [478]:
idx2vocab = {i:v for v,i in vocab2idx.items()}
idx2tag = {id:t for t,id in tag2idx.items()}


In [479]:
idx2vocab[3]

'The'

In [203]:
tm= np.zeros((len(tag2idx)+1,len(tag2idx)+1)) #+1 where 0 is start
tm

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,

In [204]:
tm.shape

(22, 22)

In [205]:
#now i want to find out how many times the row item appeared before the column item
for row in df_train.iloc[0:-1,0]:
    rowl = eval(row)
    for j in range(len(rowl)):
        if j!=0:
            _,tag1=rowl[j]
            _,tag2= rowl[j-1]
            t= tag2idx[tag1]
            tb= tag2idx[tag2]
            tm[tb,t]+=1
        if j==0:
            _,tag3=rowl[j]
            ts= tag2idx[tag3]
            tm[0,ts]+=1

In [206]:
tm

array([[0.0000e+00, 1.1910e+03, 6.5090e+03, 1.0446e+04, 2.5830e+03,
        2.1850e+03, 2.3210e+03, 5.0900e+02, 5.9040e+03, 1.9430e+03,
        2.1600e+03, 3.1300e+02, 8.4720e+03, 4.4760e+03, 3.4300e+02,
        4.4800e+02, 2.8400e+02, 1.2420e+03, 7.0000e+01, 4.5500e+02,
        5.5400e+02, 9.0000e+01],
       [0.0000e+00, 9.1300e+02, 6.1720e+03, 1.8000e+02, 6.0500e+02,
        8.5400e+02, 3.1570e+03, 1.1170e+03, 1.8480e+03, 4.5100e+02,
        1.9000e+02, 6.5000e+02, 1.2800e+02, 2.5500e+02, 4.3000e+01,
        2.0000e+00, 1.1200e+02, 6.5000e+01, 6.0000e+01, 1.4000e+01,
        1.1000e+01, 1.4400e+02],
       [0.0000e+00, 2.0160e+03, 3.6162e+04, 3.4960e+03, 3.3836e+04,
        3.1160e+03, 5.3459e+04, 9.9940e+03, 5.8578e+04, 1.2047e+04,
        3.7900e+02, 3.6590e+03, 5.0290e+03, 6.3180e+03, 2.4370e+03,
        1.5000e+01, 2.3910e+03, 3.3770e+03, 1.4220e+03, 7.7800e+02,
        1.6100e+02, 1.2300e+02],
       [0.0000e+00, 1.3250e+03, 7.0462e+04, 7.5900e+02, 6.7180e+03,
        2.8002e+0

In [207]:
row_sums = np.sum(tm, axis=1, keepdims=True) 

In [208]:
row_sums

array([[ 52498.],
       [ 16971.],
       [238793.],
       [115772.],
       [151689.],
       [ 76597.],
       [ 59172.],
       [ 12626.],
       [125174.],
       [ 27233.],
       [ 18648.],
       [ 10644.],
       [ 48844.],
       [ 48993.],
       [ 12768.],
       [   729.],
       [  6532.],
       [ 18683.],
       [  7582.],
       [  3720.],
       [  2668.],
       [   632.]])

In [209]:
row_sums[row_sums == 0] = 1

In [210]:
tm_p = tm/row_sums

In [211]:
tm_p

array([[0.00000000e+00, 2.26865785e-02, 1.23985676e-01, 1.98979009e-01,
        4.92018744e-02, 4.16206332e-02, 4.42112080e-02, 9.69560745e-03,
        1.12461427e-01, 3.70109337e-02, 4.11444245e-02, 5.96213189e-03,
        1.61377576e-01, 8.52603909e-02, 6.53358223e-03, 8.53365843e-03,
        5.40972989e-03, 2.36580441e-02, 1.33338413e-03, 8.66699684e-03,
        1.05527830e-02, 1.71435102e-03],
       [0.00000000e+00, 5.37976548e-02, 3.63679217e-01, 1.06063284e-02,
        3.56490484e-02, 5.03211361e-02, 1.86023216e-01, 6.58181604e-02,
        1.08891639e-01, 2.65747452e-02, 1.11955689e-02, 3.83006305e-02,
        7.54227800e-03, 1.50256320e-02, 2.53373402e-03, 1.17848094e-04,
        6.59949325e-03, 3.83006305e-03, 3.53544281e-03, 8.24936657e-04,
        6.48164516e-04, 8.48506275e-03],
       [0.00000000e+00, 8.44245853e-03, 1.51436600e-01, 1.46402952e-02,
        1.41695946e-01, 1.30489587e-02, 2.23871722e-01, 4.18521481e-02,
        2.45308698e-01, 5.04495525e-02, 1.58714870e-03

In [212]:
tm_p[0,20]

0.010552782963160501

In [217]:
em.shape

(58110, 22)

In [225]:
#now i want to find out how many times the row item appeared as the column item
for row in df_train.iloc[0:-1,0]:
    rowl = eval(row)
    for j in range(len(rowl)):
        word,tag=rowl[j]
        tid= tag2idx[tag]
        wid= vocab2idx[word]
        em[wid,tid]+=1

In [226]:
print(f"{vocab2idx['The']},{tag2idx['DET']}")

3,3


In [228]:
em[3][3]

6473.0

In [229]:
col_sums = np.sum(em, axis=0, keepdims=True) 
col_sums[col_sums== 0] = 1
em_p = em/col_sums

In [230]:
em_p

array([[0.00000000e+00, 5.83158386e-05, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 5.83158386e-05, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 4.66278102e-04, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       ...,
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 0.00000000e+00, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00],
       [0.00000000e+00, 0.00000000e+00, 4.16319734e-06, ...,
        0.00000000e+00, 0.00000000e+00, 0.00000000e+00]])

In [237]:
print(f"{em_p[3][3]},{idx2tag[3]},{idx2vocab[3]}")
print(f"{em_p[4][2]},{idx2tag[2]},{idx2vocab[4]}")
print(f"{em_p[3][2]},{idx2tag[2]},{idx2vocab[3]}")


0.05590485896395073,DET,The
0.0007160699417152373,NOUN,industry
0.0,NOUN,The


In [238]:
sums = np.sum(em_p, axis=0, keepdims=True) 
print(sums)
#I have kept 0 as placeholder only, so no tags there

[[0. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [239]:
sums2 = np.sum(tm_p, axis=1, keepdims=True) 
sums2

array([[1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.],
       [1.]])

In [240]:
sums2[6][0]

1.0

In [241]:
sums2.shape

(22, 1)

In [453]:
def viterbi1(row, tm_p, em_p, vocab2idx):
    rowl = eval(row)
    n = len(rowl)
    dp = np.full((len(tag2idx), n), -np.inf)
    bck_ptr = np.zeros((len(tag2idx), n), dtype=int)
    first_word, first_tag = rowl[0]
    dp[:, 0] = tm_p[0, 1:]*em_p[vocab2idx[first_word], 1:]
    for i in range(1, n):
        for tag in range(1, len(tag2idx) + 1):
            prev_pb = dp[:, i - 1]*tm_p[1:, tag]*em_p[vocab2idx[rowl[i][0]], tag]
            dp[tag - 1, i] = np.max(prev_pb)
            bck_ptr[tag - 1, i] = np.argmax(prev_pb)
    last_tag = np.argmax(dp[:, -1]) 
    tags = [last_tag]
    
    for j in range(n - 1, 0, -1):
        tags.insert(0, bck_ptr[tags[0]-1, j]+1)  

    return tags

In [456]:
def viterbi2(row, tm_p, em_p, vocab2idx):
    rowl = eval(row)
    n = len(rowl)
    dp = np.full((len(tag2idx), n), -np.inf)
    bck_ptr = np.zeros((len(tag2idx), n), dtype=int)
    first_word, first_tag = rowl[0]
    dp[:, 0] = np.log(tm_p[0, 1:]+ 1e-40) + np.log(em_p[vocab2idx[first_word], 1:]+ 1e-40)
    for i in range(1, n):
        for tag in range(1, len(tag2idx) + 1):
            prev_pb = dp[:, i - 1] + np.log(tm_p[1:, tag]+ 1e-40) + np.log(em_p[vocab2idx[rowl[i][0]], tag]+ 1e-40)
            dp[tag - 1, i] = np.max(prev_pb)
            bck_ptr[tag - 1, i] = np.argmax(prev_pb)
    last_tag = np.argmax(dp[:, -1]) 
    tags = [last_tag]
    
    for j in range(n - 1, 0, -1):
        tags.insert(0, bck_ptr[tags[0]-1, j]+1)  

    return tags


In [485]:
row=df_test.iloc[6,0]
row

'[(\'Glendora\', \'NOUN\'), ("\'\'", \'.\'), (\'--\', \'.\')]'

In [486]:
tgs=viterbi1(row,tm_p,em_p,vocab2idx)
tgs

[1, 1, 5]

In [487]:
for t in tgs:
    print(idx2tag[t])

NUM
NUM
ADJ


In [488]:
tgs=viterbi2(row,tm_p,em_p,vocab2idx)
print(tgs)
for t in tgs:
    print(idx2tag[t])

[2, 6, 5]
NOUN
.
ADJ


In [509]:
test_scores=[]
for row in df_train.iloc[0:-1,0]:
    rowl= eval(row)
    grd_t=[]
    for _,tg in rowl:
        grd_t.append(tg)
    idxs = viterbi2(row,tm_p,em_p,vocab2idx)
    pred_t=[]
    pred_t= [idx2tag.get(i)for i in idxs]
    sums=0
    for i in range(len(grd_t)):
        if(grd_t[i]==pred_t[i]): sums+=1
    score= sums/len(grd_t)
    test_scores.append(score)


In [510]:
test_scores

[0.6666666666666666,
 0.9,
 0.75,
 0.9565217391304348,
 0.7,
 0.8333333333333334,
 0.6666666666666666,
 0.9090909090909091,
 0.9090909090909091,
 0.8,
 0.625,
 0.9615384615384616,
 0.9473684210526315,
 0.8,
 0.6923076923076923,
 0.5,
 0.8,
 0.7894736842105263,
 0.625,
 0.6086956521739131,
 0.8,
 0.9285714285714286,
 0.3333333333333333,
 0.9574468085106383,
 0.875,
 0.96,
 0.8409090909090909,
 0.8709677419354839,
 0.9230769230769231,
 0.9375,
 0.7777777777777778,
 0.7222222222222222,
 0.75,
 0.9285714285714286,
 0.0,
 0.9642857142857143,
 0.9411764705882353,
 0.9545454545454546,
 0.7777777777777778,
 0.6666666666666666,
 0.9285714285714286,
 0.9444444444444444,
 0.7,
 0.5714285714285714,
 0.8421052631578947,
 0.975,
 0.5,
 0.7272727272727273,
 0.9565217391304348,
 0.0,
 0.7272727272727273,
 0.7391304347826086,
 0.9,
 0.3333333333333333,
 0.9111111111111111,
 0.8666666666666667,
 0.9230769230769231,
 0.6666666666666666,
 0.8333333333333334,
 0.7906976744186046,
 0.85,
 0.9230769230769231

In [511]:
type(test_scores)

list

In [524]:
average_score= sum(test_scores)/len(test_scores)
average_score

0.8076053374197312